<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<Authors>Kuroki-Narumi</Authors>
		<Company>LivreNoir</Company>
		<RepositoryUrl>https://github.com/Kuroki-Narumi/LivreNoirLibrary10</RepositoryUrl>
		<RootNamespace>LivreNoirLibrary.Windows.Media</RootNamespace>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<BaseOutputPath>..\..\bin</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\IndexLetters.png" />
	  <None Remove="Resources\NoteIcons.png" />
	  <None Remove="Resources\sample.bms" />
	</ItemGroup>

	<ItemGroup>
	  <Page Remove="Themes\BmsSkin\Default\7keys.xaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Include="Themes\BmsSkin\Default\7keys.xaml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\..\Media\LivreNoirLibrary.Media.Integrated\LivreNoirLibrary.Media.Integrated.csproj" />
    <ProjectReference Include="..\LivreNoirLibrary.Windows.Controls\LivreNoirLibrary.Windows.Controls.csproj" />
		<ProjectReference Include="..\LivreNoirLibrary.Windows.SourceGenerator\LivreNoirLibrary.Windows.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
  </ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\IndexLetters.png" />
	  <Resource Include="Resources\NoteIcons.png" />
	  <Resource Include="Resources\sample.bms" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Themes\BmsSkin\Default\skin_bm.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

</Project>
