<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	  <BaseOutputPath>..\..\bin</BaseOutputPath>
	  <Authors>Kuroki-Narumi</Authors>
	  <Company>LivreNoir</Company>
	  <AllowedReferenceRelatedFileExtensions>
		  *.xml;
		  *.pdb
	  </AllowedReferenceRelatedFileExtensions>
	  <ApplicationManifest>app.manifest</ApplicationManifest>
	  <ApplicationIcon>icon.ico</ApplicationIcon>
	  <RootNamespace>LivreNoir.Clock</RootNamespace>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
	  <Content Include="icon.ico" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\..\Windows\LivreNoirLibrary.Windows.Controls\LivreNoirLibrary.Windows.Controls.csproj" />
  </ItemGroup>

</Project>
