<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<Authors>Kuroki-Narumi</Authors>
		<Company>LivreNoir</Company>
		<RepositoryUrl>https://github.com/Kuroki-Narumi/LivreNoirLibrary10</RepositoryUrl>
		<RootNamespace>LivreNoirLibrary.Windows.Media</RootNamespace>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<BaseOutputPath>..\..\bin</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Effects\Shaders\transparent.ps" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Media\LivreNoirLibrary.Media.Bitmap\LivreNoirLibrary.Media.Bitmap.csproj" />
	  <ProjectReference Include="..\LivreNoirLibrary.Windows.Core\LivreNoirLibrary.Windows.Core.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Effects\Shaders\transparent.ps" />
	</ItemGroup>

</Project>
