using System;

namespace LivreNoirLibrary.Media.Bms.Play
{
    public enum TimerId
    {
        None,

        Scene_Start,
        Scene_Terminate,

        Play_LoadingStart = TimerIdOffsets.Play + 1,
        Play_LoadingFinish,
        Play_MusicStart,
        Play_Beat,
        Play_FullCombo,

        Play_Gauge_Gain,
        Play_Gauge_Low,
        Play_Gauge_High,
        Play_Gauge_Max,

        Play_Judge = TimerIdOffsets.JudgeBegin + TimerIdOffsets.Judge,
        Play_Early = TimerIdOffsets.JudgeBegin + TimerIdOffsets.Early,
        Play_Late = TimerIdOffsets.JudgeBegin + TimerIdOffsets.Late,
        Play_Miss = TimerIdOffsets.JudgeBegin + TimerIdOffsets.Miss,

        Play_1P_Judge = TimerIdOffsets.JudgeBegin + 10 + TimerIdOffsets.Judge,
        Play_1P_Early = TimerIdOffsets.JudgeBegin + 10 + TimerIdOffsets.Early,
        Play_1P_Late = TimerIdOffsets.JudgeBegin + 10 + TimerIdOffsets.Late,
        Play_1P_Miss = TimerIdOffsets.JudgeBegin + 10 + TimerIdOffsets.Miss,

        Play_2P_Judge = TimerIdOffsets.JudgeBegin + 20 + TimerIdOffsets.Judge,
        Play_2P_Early = TimerIdOffsets.JudgeBegin + 20 + TimerIdOffsets.Early,
        Play_2P_Late = TimerIdOffsets.JudgeBegin + 20 + TimerIdOffsets.Late,
        Play_2P_Miss = TimerIdOffsets.JudgeBegin + 20 + TimerIdOffsets.Miss,

        Play_3P_Judge = TimerIdOffsets.JudgeBegin + 30 + TimerIdOffsets.Judge,
        Play_3P_Early = TimerIdOffsets.JudgeBegin + 30 + TimerIdOffsets.Early,
        Play_3P_Late = TimerIdOffsets.JudgeBegin + 30 + TimerIdOffsets.Late,
        Play_3P_Miss = TimerIdOffsets.JudgeBegin + 30 + TimerIdOffsets.Miss,

        Play_4P_Judge = TimerIdOffsets.JudgeBegin + 40 + TimerIdOffsets.Judge,
        Play_4P_Early = TimerIdOffsets.JudgeBegin + 40 + TimerIdOffsets.Early,
        Play_4P_Late = TimerIdOffsets.JudgeBegin + 40 + TimerIdOffsets.Late,
        Play_4P_Miss = TimerIdOffsets.JudgeBegin + 40 + TimerIdOffsets.Miss,

        Play_5P_Judge = TimerIdOffsets.JudgeBegin + 50 + TimerIdOffsets.Judge,
        Play_5P_Early = TimerIdOffsets.JudgeBegin + 50 + TimerIdOffsets.Early,
        Play_5P_Late = TimerIdOffsets.JudgeBegin + 50 + TimerIdOffsets.Late,
        Play_5P_Miss = TimerIdOffsets.JudgeBegin + 50 + TimerIdOffsets.Miss,

        Play_6P_Judge = TimerIdOffsets.JudgeBegin + 60 + TimerIdOffsets.Judge,
        Play_6P_Early = TimerIdOffsets.JudgeBegin + 60 + TimerIdOffsets.Early,
        Play_6P_Late = TimerIdOffsets.JudgeBegin + 60 + TimerIdOffsets.Late,
        Play_6P_Miss = TimerIdOffsets.JudgeBegin + 60 + TimerIdOffsets.Miss,

        Play_7P_Judge = TimerIdOffsets.JudgeBegin + 70 + TimerIdOffsets.Judge,
        Play_7P_Early = TimerIdOffsets.JudgeBegin + 70 + TimerIdOffsets.Early,
        Play_7P_Late = TimerIdOffsets.JudgeBegin + 70 + TimerIdOffsets.Late,
        Play_7P_Miss = TimerIdOffsets.JudgeBegin + 70 + TimerIdOffsets.Miss,

        Play_8P_Judge = TimerIdOffsets.JudgeBegin + 80 + TimerIdOffsets.Judge,
        Play_8P_Early = TimerIdOffsets.JudgeBegin + 80 + TimerIdOffsets.Early,
        Play_8P_Late = TimerIdOffsets.JudgeBegin + 80 + TimerIdOffsets.Late,
        Play_8P_Miss = TimerIdOffsets.JudgeBegin + 80 + TimerIdOffsets.Miss,

        Play_Button1_Press = TimerIdOffsets.ButtonBegin + 10 + TimerIdOffsets.Press,
        Play_Button1_Release = TimerIdOffsets.ButtonBegin + 10 + TimerIdOffsets.Release,
        Play_Button1_Bomb = TimerIdOffsets.ButtonBegin + 10 + TimerIdOffsets.Bomb,
        Play_Button1_LongBomb = TimerIdOffsets.ButtonBegin + 10 + TimerIdOffsets.LongBomb,
        Play_Button1_Mine = TimerIdOffsets.ButtonBegin + 10 + TimerIdOffsets.Mine,

        Play_Button2_Press = TimerIdOffsets.ButtonBegin + 20 + TimerIdOffsets.Press,
        Play_Button2_Release = TimerIdOffsets.ButtonBegin + 20 + TimerIdOffsets.Release,
        Play_Button2_Bomb = TimerIdOffsets.ButtonBegin + 20 + TimerIdOffsets.Bomb,
        Play_Button2_LongBomb = TimerIdOffsets.ButtonBegin + 20 + TimerIdOffsets.LongBomb,
        Play_Button2_Mine = TimerIdOffsets.ButtonBegin + 20 + TimerIdOffsets.Mine,

        Play_Button3_Press = TimerIdOffsets.ButtonBegin + 30 + TimerIdOffsets.Press,
        Play_Button3_Release = TimerIdOffsets.ButtonBegin + 30 + TimerIdOffsets.Release,
        Play_Button3_Bomb = TimerIdOffsets.ButtonBegin + 30 + TimerIdOffsets.Bomb,
        Play_Button3_LongBomb = TimerIdOffsets.ButtonBegin + 30 + TimerIdOffsets.LongBomb,
        Play_Button3_Mine = TimerIdOffsets.ButtonBegin + 30 + TimerIdOffsets.Mine,

        Play_Button4_Press = TimerIdOffsets.ButtonBegin + 40 + TimerIdOffsets.Press,
        Play_Button4_Release = TimerIdOffsets.ButtonBegin + 40 + TimerIdOffsets.Release,
        Play_Button4_Bomb = TimerIdOffsets.ButtonBegin + 40 + TimerIdOffsets.Bomb,
        Play_Button4_LongBomb = TimerIdOffsets.ButtonBegin + 40 + TimerIdOffsets.LongBomb,
        Play_Button4_Mine = TimerIdOffsets.ButtonBegin + 40 + TimerIdOffsets.Mine,

        Play_Button5_Press = TimerIdOffsets.ButtonBegin + 50 + TimerIdOffsets.Press,
        Play_Button5_Release = TimerIdOffsets.ButtonBegin + 50 + TimerIdOffsets.Release,
        Play_Button5_Bomb = TimerIdOffsets.ButtonBegin + 50 + TimerIdOffsets.Bomb,
        Play_Button5_LongBomb = TimerIdOffsets.ButtonBegin + 50 + TimerIdOffsets.LongBomb,
        Play_Button5_Mine = TimerIdOffsets.ButtonBegin + 50 + TimerIdOffsets.Mine,

        Play_Button6_Press = TimerIdOffsets.ButtonBegin + 60 + TimerIdOffsets.Press,
        Play_Button6_Release = TimerIdOffsets.ButtonBegin + 60 + TimerIdOffsets.Release,
        Play_Button6_Bomb = TimerIdOffsets.ButtonBegin + 60 + TimerIdOffsets.Bomb,
        Play_Button6_LongBomb = TimerIdOffsets.ButtonBegin + 60 + TimerIdOffsets.LongBomb,
        Play_Button6_Mine = TimerIdOffsets.ButtonBegin + 60 + TimerIdOffsets.Mine,

        Play_Button7_Press = TimerIdOffsets.ButtonBegin + 70 + TimerIdOffsets.Press,
        Play_Button7_Release = TimerIdOffsets.ButtonBegin + 70 + TimerIdOffsets.Release,
        Play_Button7_Bomb = TimerIdOffsets.ButtonBegin + 70 + TimerIdOffsets.Bomb,
        Play_Button7_LongBomb = TimerIdOffsets.ButtonBegin + 70 + TimerIdOffsets.LongBomb,
        Play_Button7_Mine = TimerIdOffsets.ButtonBegin + 70 + TimerIdOffsets.Mine,

        Play_Button8_Press = TimerIdOffsets.ButtonBegin + 80 + TimerIdOffsets.Press,
        Play_Button8_Release = TimerIdOffsets.ButtonBegin + 80 + TimerIdOffsets.Release,
        Play_Button8_Bomb = TimerIdOffsets.ButtonBegin + 80 + TimerIdOffsets.Bomb,
        Play_Button8_LongBomb = TimerIdOffsets.ButtonBegin + 80 + TimerIdOffsets.LongBomb,
        Play_Button8_Mine = TimerIdOffsets.ButtonBegin + 80 + TimerIdOffsets.Mine,

        Play_Button9_Press = TimerIdOffsets.ButtonBegin + 90 + TimerIdOffsets.Press,
        Play_Button9_Release = TimerIdOffsets.ButtonBegin + 90 + TimerIdOffsets.Release,
        Play_Button9_Bomb = TimerIdOffsets.ButtonBegin + 90 + TimerIdOffsets.Bomb,
        Play_Button9_LongBomb = TimerIdOffsets.ButtonBegin + 90 + TimerIdOffsets.LongBomb,
        Play_Button9_Mine = TimerIdOffsets.ButtonBegin + 90 + TimerIdOffsets.Mine,

        Play_Button10_Press = TimerIdOffsets.ButtonBegin + 100 + TimerIdOffsets.Press,
        Play_Button10_Release = TimerIdOffsets.ButtonBegin + 100 + TimerIdOffsets.Release,
        Play_Button10_Bomb = TimerIdOffsets.ButtonBegin + 100 + TimerIdOffsets.Bomb,
        Play_Button10_LongBomb = TimerIdOffsets.ButtonBegin + 100 + TimerIdOffsets.LongBomb,
        Play_Button10_Mine = TimerIdOffsets.ButtonBegin + 100 + TimerIdOffsets.Mine,

        Play_Button11_Press = TimerIdOffsets.ButtonBegin + 110 + TimerIdOffsets.Press,
        Play_Button11_Release = TimerIdOffsets.ButtonBegin + 110 + TimerIdOffsets.Release,
        Play_Button11_Bomb = TimerIdOffsets.ButtonBegin + 110 + TimerIdOffsets.Bomb,
        Play_Button11_LongBomb = TimerIdOffsets.ButtonBegin + 110 + TimerIdOffsets.LongBomb,
        Play_Button11_Mine = TimerIdOffsets.ButtonBegin + 110 + TimerIdOffsets.Mine,

        Play_Button12_Press = TimerIdOffsets.ButtonBegin + 120 + TimerIdOffsets.Press,
        Play_Button12_Release = TimerIdOffsets.ButtonBegin + 120 + TimerIdOffsets.Release,
        Play_Button12_Bomb = TimerIdOffsets.ButtonBegin + 120 + TimerIdOffsets.Bomb,
        Play_Button12_LongBomb = TimerIdOffsets.ButtonBegin + 120 + TimerIdOffsets.LongBomb,
        Play_Button12_Mine = TimerIdOffsets.ButtonBegin + 120 + TimerIdOffsets.Mine,

        Play_Button13_Press = TimerIdOffsets.ButtonBegin + 130 + TimerIdOffsets.Press,
        Play_Button13_Release = TimerIdOffsets.ButtonBegin + 130 + TimerIdOffsets.Release,
        Play_Button13_Bomb = TimerIdOffsets.ButtonBegin + 130 + TimerIdOffsets.Bomb,
        Play_Button13_LongBomb = TimerIdOffsets.ButtonBegin + 130 + TimerIdOffsets.LongBomb,
        Play_Button13_Mine = TimerIdOffsets.ButtonBegin + 130 + TimerIdOffsets.Mine,

        Play_Button14_Press = TimerIdOffsets.ButtonBegin + 140 + TimerIdOffsets.Press,
        Play_Button14_Release = TimerIdOffsets.ButtonBegin + 140 + TimerIdOffsets.Release,
        Play_Button14_Bomb = TimerIdOffsets.ButtonBegin + 140 + TimerIdOffsets.Bomb,
        Play_Button14_LongBomb = TimerIdOffsets.ButtonBegin + 140 + TimerIdOffsets.LongBomb,
        Play_Button14_Mine = TimerIdOffsets.ButtonBegin + 140 + TimerIdOffsets.Mine,

        Play_Button15_Press = TimerIdOffsets.ButtonBegin + 150 + TimerIdOffsets.Press,
        Play_Button15_Release = TimerIdOffsets.ButtonBegin + 150 + TimerIdOffsets.Release,
        Play_Button15_Bomb = TimerIdOffsets.ButtonBegin + 150 + TimerIdOffsets.Bomb,
        Play_Button15_LongBomb = TimerIdOffsets.ButtonBegin + 150 + TimerIdOffsets.LongBomb,
        Play_Button15_Mine = TimerIdOffsets.ButtonBegin + 150 + TimerIdOffsets.Mine,

        Play_Button16_Press = TimerIdOffsets.ButtonBegin + 160 + TimerIdOffsets.Press,
        Play_Button16_Release = TimerIdOffsets.ButtonBegin + 160 + TimerIdOffsets.Release,
        Play_Button16_Bomb = TimerIdOffsets.ButtonBegin + 160 + TimerIdOffsets.Bomb,
        Play_Button16_LongBomb = TimerIdOffsets.ButtonBegin + 160 + TimerIdOffsets.LongBomb,
        Play_Button16_Mine = TimerIdOffsets.ButtonBegin + 160 + TimerIdOffsets.Mine,

        Play_Button17_Press = TimerIdOffsets.ButtonBegin + 170 + TimerIdOffsets.Press,
        Play_Button17_Release = TimerIdOffsets.ButtonBegin + 170 + TimerIdOffsets.Release,
        Play_Button17_Bomb = TimerIdOffsets.ButtonBegin + 170 + TimerIdOffsets.Bomb,
        Play_Button17_LongBomb = TimerIdOffsets.ButtonBegin + 170 + TimerIdOffsets.LongBomb,
        Play_Button17_Mine = TimerIdOffsets.ButtonBegin + 170 + TimerIdOffsets.Mine,

        Play_Button18_Press = TimerIdOffsets.ButtonBegin + 180 + TimerIdOffsets.Press,
        Play_Button18_Release = TimerIdOffsets.ButtonBegin + 180 + TimerIdOffsets.Release,
        Play_Button18_Bomb = TimerIdOffsets.ButtonBegin + 180 + TimerIdOffsets.Bomb,
        Play_Button18_LongBomb = TimerIdOffsets.ButtonBegin + 180 + TimerIdOffsets.LongBomb,
        Play_Button18_Mine = TimerIdOffsets.ButtonBegin + 180 + TimerIdOffsets.Mine,

        Play_Button19_Press = TimerIdOffsets.ButtonBegin + 190 + TimerIdOffsets.Press,
        Play_Button19_Release = TimerIdOffsets.ButtonBegin + 190 + TimerIdOffsets.Release,
        Play_Button19_Bomb = TimerIdOffsets.ButtonBegin + 190 + TimerIdOffsets.Bomb,
        Play_Button19_LongBomb = TimerIdOffsets.ButtonBegin + 190 + TimerIdOffsets.LongBomb,
        Play_Button19_Mine = TimerIdOffsets.ButtonBegin + 190 + TimerIdOffsets.Mine,

        Play_Button20_Press = TimerIdOffsets.ButtonBegin + 200 + TimerIdOffsets.Press,
        Play_Button20_Release = TimerIdOffsets.ButtonBegin + 200 + TimerIdOffsets.Release,
        Play_Button20_Bomb = TimerIdOffsets.ButtonBegin + 200 + TimerIdOffsets.Bomb,
        Play_Button20_LongBomb = TimerIdOffsets.ButtonBegin + 200 + TimerIdOffsets.LongBomb,
        Play_Button20_Mine = TimerIdOffsets.ButtonBegin + 200 + TimerIdOffsets.Mine,

        Play_Button21_Press = TimerIdOffsets.ButtonBegin + 210 + TimerIdOffsets.Press,
        Play_Button21_Release = TimerIdOffsets.ButtonBegin + 210 + TimerIdOffsets.Release,
        Play_Button21_Bomb = TimerIdOffsets.ButtonBegin + 210 + TimerIdOffsets.Bomb,
        Play_Button21_LongBomb = TimerIdOffsets.ButtonBegin + 210 + TimerIdOffsets.LongBomb,
        Play_Button21_Mine = TimerIdOffsets.ButtonBegin + 210 + TimerIdOffsets.Mine,

        Play_Button22_Press = TimerIdOffsets.ButtonBegin + 220 + TimerIdOffsets.Press,
        Play_Button22_Release = TimerIdOffsets.ButtonBegin + 220 + TimerIdOffsets.Release,
        Play_Button22_Bomb = TimerIdOffsets.ButtonBegin + 220 + TimerIdOffsets.Bomb,
        Play_Button22_LongBomb = TimerIdOffsets.ButtonBegin + 220 + TimerIdOffsets.LongBomb,
        Play_Button22_Mine = TimerIdOffsets.ButtonBegin + 220 + TimerIdOffsets.Mine,

        Play_Button23_Press = TimerIdOffsets.ButtonBegin + 230 + TimerIdOffsets.Press,
        Play_Button23_Release = TimerIdOffsets.ButtonBegin + 230 + TimerIdOffsets.Release,
        Play_Button23_Bomb = TimerIdOffsets.ButtonBegin + 230 + TimerIdOffsets.Bomb,
        Play_Button23_LongBomb = TimerIdOffsets.ButtonBegin + 230 + TimerIdOffsets.LongBomb,
        Play_Button23_Mine = TimerIdOffsets.ButtonBegin + 230 + TimerIdOffsets.Mine,

        Play_Button24_Press = TimerIdOffsets.ButtonBegin + 240 + TimerIdOffsets.Press,
        Play_Button24_Release = TimerIdOffsets.ButtonBegin + 240 + TimerIdOffsets.Release,
        Play_Button24_Bomb = TimerIdOffsets.ButtonBegin + 240 + TimerIdOffsets.Bomb,
        Play_Button24_LongBomb = TimerIdOffsets.ButtonBegin + 240 + TimerIdOffsets.LongBomb,
        Play_Button24_Mine = TimerIdOffsets.ButtonBegin + 240 + TimerIdOffsets.Mine,

        Play_Button25_Press = TimerIdOffsets.ButtonBegin + 250 + TimerIdOffsets.Press,
        Play_Button25_Release = TimerIdOffsets.ButtonBegin + 250 + TimerIdOffsets.Release,
        Play_Button25_Bomb = TimerIdOffsets.ButtonBegin + 250 + TimerIdOffsets.Bomb,
        Play_Button25_LongBomb = TimerIdOffsets.ButtonBegin + 250 + TimerIdOffsets.LongBomb,
        Play_Button25_Mine = TimerIdOffsets.ButtonBegin + 250 + TimerIdOffsets.Mine,

        Play_Button26_Press = TimerIdOffsets.ButtonBegin + 260 + TimerIdOffsets.Press,
        Play_Button26_Release = TimerIdOffsets.ButtonBegin + 260 + TimerIdOffsets.Release,
        Play_Button26_Bomb = TimerIdOffsets.ButtonBegin + 260 + TimerIdOffsets.Bomb,
        Play_Button26_LongBomb = TimerIdOffsets.ButtonBegin + 260 + TimerIdOffsets.LongBomb,
        Play_Button26_Mine = TimerIdOffsets.ButtonBegin + 260 + TimerIdOffsets.Mine,

        Play_Button27_Press = TimerIdOffsets.ButtonBegin + 270 + TimerIdOffsets.Press,
        Play_Button27_Release = TimerIdOffsets.ButtonBegin + 270 + TimerIdOffsets.Release,
        Play_Button27_Bomb = TimerIdOffsets.ButtonBegin + 270 + TimerIdOffsets.Bomb,
        Play_Button27_LongBomb = TimerIdOffsets.ButtonBegin + 270 + TimerIdOffsets.LongBomb,
        Play_Button27_Mine = TimerIdOffsets.ButtonBegin + 270 + TimerIdOffsets.Mine,

        Play_Button28_Press = TimerIdOffsets.ButtonBegin + 280 + TimerIdOffsets.Press,
        Play_Button28_Release = TimerIdOffsets.ButtonBegin + 280 + TimerIdOffsets.Release,
        Play_Button28_Bomb = TimerIdOffsets.ButtonBegin + 280 + TimerIdOffsets.Bomb,
        Play_Button28_LongBomb = TimerIdOffsets.ButtonBegin + 280 + TimerIdOffsets.LongBomb,
        Play_Button28_Mine = TimerIdOffsets.ButtonBegin + 280 + TimerIdOffsets.Mine,

        Play_Button29_Press = TimerIdOffsets.ButtonBegin + 290 + TimerIdOffsets.Press,
        Play_Button29_Release = TimerIdOffsets.ButtonBegin + 290 + TimerIdOffsets.Release,
        Play_Button29_Bomb = TimerIdOffsets.ButtonBegin + 290 + TimerIdOffsets.Bomb,
        Play_Button29_LongBomb = TimerIdOffsets.ButtonBegin + 290 + TimerIdOffsets.LongBomb,
        Play_Button29_Mine = TimerIdOffsets.ButtonBegin + 290 + TimerIdOffsets.Mine,

        Play_Button30_Press = TimerIdOffsets.ButtonBegin + 300 + TimerIdOffsets.Press,
        Play_Button30_Release = TimerIdOffsets.ButtonBegin + 300 + TimerIdOffsets.Release,
        Play_Button30_Bomb = TimerIdOffsets.ButtonBegin + 300 + TimerIdOffsets.Bomb,
        Play_Button30_LongBomb = TimerIdOffsets.ButtonBegin + 300 + TimerIdOffsets.LongBomb,
        Play_Button30_Mine = TimerIdOffsets.ButtonBegin + 300 + TimerIdOffsets.Mine,

        Play_Button31_Press = TimerIdOffsets.ButtonBegin + 310 + TimerIdOffsets.Press,
        Play_Button31_Release = TimerIdOffsets.ButtonBegin + 310 + TimerIdOffsets.Release,
        Play_Button31_Bomb = TimerIdOffsets.ButtonBegin + 310 + TimerIdOffsets.Bomb,
        Play_Button31_LongBomb = TimerIdOffsets.ButtonBegin + 310 + TimerIdOffsets.LongBomb,
        Play_Button31_Mine = TimerIdOffsets.ButtonBegin + 310 + TimerIdOffsets.Mine,

        Play_Button32_Press = TimerIdOffsets.ButtonBegin + 320 + TimerIdOffsets.Press,
        Play_Button32_Release = TimerIdOffsets.ButtonBegin + 320 + TimerIdOffsets.Release,
        Play_Button32_Bomb = TimerIdOffsets.ButtonBegin + 320 + TimerIdOffsets.Bomb,
        Play_Button32_LongBomb = TimerIdOffsets.ButtonBegin + 320 + TimerIdOffsets.LongBomb,
        Play_Button32_Mine = TimerIdOffsets.ButtonBegin + 320 + TimerIdOffsets.Mine,

        Play_Button33_Press = TimerIdOffsets.ButtonBegin + 330 + TimerIdOffsets.Press,
        Play_Button33_Release = TimerIdOffsets.ButtonBegin + 330 + TimerIdOffsets.Release,
        Play_Button33_Bomb = TimerIdOffsets.ButtonBegin + 330 + TimerIdOffsets.Bomb,
        Play_Button33_LongBomb = TimerIdOffsets.ButtonBegin + 330 + TimerIdOffsets.LongBomb,
        Play_Button33_Mine = TimerIdOffsets.ButtonBegin + 330 + TimerIdOffsets.Mine,

        Play_Button34_Press = TimerIdOffsets.ButtonBegin + 340 + TimerIdOffsets.Press,
        Play_Button34_Release = TimerIdOffsets.ButtonBegin + 340 + TimerIdOffsets.Release,
        Play_Button34_Bomb = TimerIdOffsets.ButtonBegin + 340 + TimerIdOffsets.Bomb,
        Play_Button34_LongBomb = TimerIdOffsets.ButtonBegin + 340 + TimerIdOffsets.LongBomb,
        Play_Button34_Mine = TimerIdOffsets.ButtonBegin + 340 + TimerIdOffsets.Mine,

        Play_Button35_Press = TimerIdOffsets.ButtonBegin + 350 + TimerIdOffsets.Press,
        Play_Button35_Release = TimerIdOffsets.ButtonBegin + 350 + TimerIdOffsets.Release,
        Play_Button35_Bomb = TimerIdOffsets.ButtonBegin + 350 + TimerIdOffsets.Bomb,
        Play_Button35_LongBomb = TimerIdOffsets.ButtonBegin + 350 + TimerIdOffsets.LongBomb,
        Play_Button35_Mine = TimerIdOffsets.ButtonBegin + 350 + TimerIdOffsets.Mine,

        Play_Button36_Press = TimerIdOffsets.ButtonBegin + 360 + TimerIdOffsets.Press,
        Play_Button36_Release = TimerIdOffsets.ButtonBegin + 360 + TimerIdOffsets.Release,
        Play_Button36_Bomb = TimerIdOffsets.ButtonBegin + 360 + TimerIdOffsets.Bomb,
        Play_Button36_LongBomb = TimerIdOffsets.ButtonBegin + 360 + TimerIdOffsets.LongBomb,
        Play_Button36_Mine = TimerIdOffsets.ButtonBegin + 360 + TimerIdOffsets.Mine,

        Play_Button37_Press = TimerIdOffsets.ButtonBegin + 370 + TimerIdOffsets.Press,
        Play_Button37_Release = TimerIdOffsets.ButtonBegin + 370 + TimerIdOffsets.Release,
        Play_Button37_Bomb = TimerIdOffsets.ButtonBegin + 370 + TimerIdOffsets.Bomb,
        Play_Button37_LongBomb = TimerIdOffsets.ButtonBegin + 370 + TimerIdOffsets.LongBomb,
        Play_Button37_Mine = TimerIdOffsets.ButtonBegin + 370 + TimerIdOffsets.Mine,

        Play_Button38_Press = TimerIdOffsets.ButtonBegin + 380 + TimerIdOffsets.Press,
        Play_Button38_Release = TimerIdOffsets.ButtonBegin + 380 + TimerIdOffsets.Release,
        Play_Button38_Bomb = TimerIdOffsets.ButtonBegin + 380 + TimerIdOffsets.Bomb,
        Play_Button38_LongBomb = TimerIdOffsets.ButtonBegin + 380 + TimerIdOffsets.LongBomb,
        Play_Button38_Mine = TimerIdOffsets.ButtonBegin + 380 + TimerIdOffsets.Mine,

        Play_Button39_Press = TimerIdOffsets.ButtonBegin + 390 + TimerIdOffsets.Press,
        Play_Button39_Release = TimerIdOffsets.ButtonBegin + 390 + TimerIdOffsets.Release,
        Play_Button39_Bomb = TimerIdOffsets.ButtonBegin + 390 + TimerIdOffsets.Bomb,
        Play_Button39_LongBomb = TimerIdOffsets.ButtonBegin + 390 + TimerIdOffsets.LongBomb,
        Play_Button39_Mine = TimerIdOffsets.ButtonBegin + 390 + TimerIdOffsets.Mine,

        Play_Button40_Press = TimerIdOffsets.ButtonBegin + 400 + TimerIdOffsets.Press,
        Play_Button40_Release = TimerIdOffsets.ButtonBegin + 400 + TimerIdOffsets.Release,
        Play_Button40_Bomb = TimerIdOffsets.ButtonBegin + 400 + TimerIdOffsets.Bomb,
        Play_Button40_LongBomb = TimerIdOffsets.ButtonBegin + 400 + TimerIdOffsets.LongBomb,
        Play_Button40_Mine = TimerIdOffsets.ButtonBegin + 400 + TimerIdOffsets.Mine,

        Play_Button41_Press = TimerIdOffsets.ButtonBegin + 410 + TimerIdOffsets.Press,
        Play_Button41_Release = TimerIdOffsets.ButtonBegin + 410 + TimerIdOffsets.Release,
        Play_Button41_Bomb = TimerIdOffsets.ButtonBegin + 410 + TimerIdOffsets.Bomb,
        Play_Button41_LongBomb = TimerIdOffsets.ButtonBegin + 410 + TimerIdOffsets.LongBomb,
        Play_Button41_Mine = TimerIdOffsets.ButtonBegin + 410 + TimerIdOffsets.Mine,

        Play_Button42_Press = TimerIdOffsets.ButtonBegin + 420 + TimerIdOffsets.Press,
        Play_Button42_Release = TimerIdOffsets.ButtonBegin + 420 + TimerIdOffsets.Release,
        Play_Button42_Bomb = TimerIdOffsets.ButtonBegin + 420 + TimerIdOffsets.Bomb,
        Play_Button42_LongBomb = TimerIdOffsets.ButtonBegin + 420 + TimerIdOffsets.LongBomb,
        Play_Button42_Mine = TimerIdOffsets.ButtonBegin + 420 + TimerIdOffsets.Mine,

        Play_Button43_Press = TimerIdOffsets.ButtonBegin + 430 + TimerIdOffsets.Press,
        Play_Button43_Release = TimerIdOffsets.ButtonBegin + 430 + TimerIdOffsets.Release,
        Play_Button43_Bomb = TimerIdOffsets.ButtonBegin + 430 + TimerIdOffsets.Bomb,
        Play_Button43_LongBomb = TimerIdOffsets.ButtonBegin + 430 + TimerIdOffsets.LongBomb,
        Play_Button43_Mine = TimerIdOffsets.ButtonBegin + 430 + TimerIdOffsets.Mine,

        Play_Button44_Press = TimerIdOffsets.ButtonBegin + 440 + TimerIdOffsets.Press,
        Play_Button44_Release = TimerIdOffsets.ButtonBegin + 440 + TimerIdOffsets.Release,
        Play_Button44_Bomb = TimerIdOffsets.ButtonBegin + 440 + TimerIdOffsets.Bomb,
        Play_Button44_LongBomb = TimerIdOffsets.ButtonBegin + 440 + TimerIdOffsets.LongBomb,
        Play_Button44_Mine = TimerIdOffsets.ButtonBegin + 440 + TimerIdOffsets.Mine,

        Play_Button45_Press = TimerIdOffsets.ButtonBegin + 450 + TimerIdOffsets.Press,
        Play_Button45_Release = TimerIdOffsets.ButtonBegin + 450 + TimerIdOffsets.Release,
        Play_Button45_Bomb = TimerIdOffsets.ButtonBegin + 450 + TimerIdOffsets.Bomb,
        Play_Button45_LongBomb = TimerIdOffsets.ButtonBegin + 450 + TimerIdOffsets.LongBomb,
        Play_Button45_Mine = TimerIdOffsets.ButtonBegin + 450 + TimerIdOffsets.Mine,

        Play_Button46_Press = TimerIdOffsets.ButtonBegin + 460 + TimerIdOffsets.Press,
        Play_Button46_Release = TimerIdOffsets.ButtonBegin + 460 + TimerIdOffsets.Release,
        Play_Button46_Bomb = TimerIdOffsets.ButtonBegin + 460 + TimerIdOffsets.Bomb,
        Play_Button46_LongBomb = TimerIdOffsets.ButtonBegin + 460 + TimerIdOffsets.LongBomb,
        Play_Button46_Mine = TimerIdOffsets.ButtonBegin + 460 + TimerIdOffsets.Mine,

        Play_Button47_Press = TimerIdOffsets.ButtonBegin + 470 + TimerIdOffsets.Press,
        Play_Button47_Release = TimerIdOffsets.ButtonBegin + 470 + TimerIdOffsets.Release,
        Play_Button47_Bomb = TimerIdOffsets.ButtonBegin + 470 + TimerIdOffsets.Bomb,
        Play_Button47_LongBomb = TimerIdOffsets.ButtonBegin + 470 + TimerIdOffsets.LongBomb,
        Play_Button47_Mine = TimerIdOffsets.ButtonBegin + 470 + TimerIdOffsets.Mine,

        Play_Button48_Press = TimerIdOffsets.ButtonBegin + 480 + TimerIdOffsets.Press,
        Play_Button48_Release = TimerIdOffsets.ButtonBegin + 480 + TimerIdOffsets.Release,
        Play_Button48_Bomb = TimerIdOffsets.ButtonBegin + 480 + TimerIdOffsets.Bomb,
        Play_Button48_LongBomb = TimerIdOffsets.ButtonBegin + 480 + TimerIdOffsets.LongBomb,
        Play_Button48_Mine = TimerIdOffsets.ButtonBegin + 480 + TimerIdOffsets.Mine,

        Play_Button49_Press = TimerIdOffsets.ButtonBegin + 490 + TimerIdOffsets.Press,
        Play_Button49_Release = TimerIdOffsets.ButtonBegin + 490 + TimerIdOffsets.Release,
        Play_Button49_Bomb = TimerIdOffsets.ButtonBegin + 490 + TimerIdOffsets.Bomb,
        Play_Button49_LongBomb = TimerIdOffsets.ButtonBegin + 490 + TimerIdOffsets.LongBomb,
        Play_Button49_Mine = TimerIdOffsets.ButtonBegin + 490 + TimerIdOffsets.Mine,

        Play_Button50_Press = TimerIdOffsets.ButtonBegin + 500 + TimerIdOffsets.Press,
        Play_Button50_Release = TimerIdOffsets.ButtonBegin + 500 + TimerIdOffsets.Release,
        Play_Button50_Bomb = TimerIdOffsets.ButtonBegin + 500 + TimerIdOffsets.Bomb,
        Play_Button50_LongBomb = TimerIdOffsets.ButtonBegin + 500 + TimerIdOffsets.LongBomb,
        Play_Button50_Mine = TimerIdOffsets.ButtonBegin + 500 + TimerIdOffsets.Mine,

        Play_Button51_Press = TimerIdOffsets.ButtonBegin + 510 + TimerIdOffsets.Press,
        Play_Button51_Release = TimerIdOffsets.ButtonBegin + 510 + TimerIdOffsets.Release,
        Play_Button51_Bomb = TimerIdOffsets.ButtonBegin + 510 + TimerIdOffsets.Bomb,
        Play_Button51_LongBomb = TimerIdOffsets.ButtonBegin + 510 + TimerIdOffsets.LongBomb,
        Play_Button51_Mine = TimerIdOffsets.ButtonBegin + 510 + TimerIdOffsets.Mine,

        Play_Button52_Press = TimerIdOffsets.ButtonBegin + 520 + TimerIdOffsets.Press,
        Play_Button52_Release = TimerIdOffsets.ButtonBegin + 520 + TimerIdOffsets.Release,
        Play_Button52_Bomb = TimerIdOffsets.ButtonBegin + 520 + TimerIdOffsets.Bomb,
        Play_Button52_LongBomb = TimerIdOffsets.ButtonBegin + 520 + TimerIdOffsets.LongBomb,
        Play_Button52_Mine = TimerIdOffsets.ButtonBegin + 520 + TimerIdOffsets.Mine,

        Play_Button53_Press = TimerIdOffsets.ButtonBegin + 530 + TimerIdOffsets.Press,
        Play_Button53_Release = TimerIdOffsets.ButtonBegin + 530 + TimerIdOffsets.Release,
        Play_Button53_Bomb = TimerIdOffsets.ButtonBegin + 530 + TimerIdOffsets.Bomb,
        Play_Button53_LongBomb = TimerIdOffsets.ButtonBegin + 530 + TimerIdOffsets.LongBomb,
        Play_Button53_Mine = TimerIdOffsets.ButtonBegin + 530 + TimerIdOffsets.Mine,

        Play_Button54_Press = TimerIdOffsets.ButtonBegin + 540 + TimerIdOffsets.Press,
        Play_Button54_Release = TimerIdOffsets.ButtonBegin + 540 + TimerIdOffsets.Release,
        Play_Button54_Bomb = TimerIdOffsets.ButtonBegin + 540 + TimerIdOffsets.Bomb,
        Play_Button54_LongBomb = TimerIdOffsets.ButtonBegin + 540 + TimerIdOffsets.LongBomb,
        Play_Button54_Mine = TimerIdOffsets.ButtonBegin + 540 + TimerIdOffsets.Mine,

        Play_Button55_Press = TimerIdOffsets.ButtonBegin + 550 + TimerIdOffsets.Press,
        Play_Button55_Release = TimerIdOffsets.ButtonBegin + 550 + TimerIdOffsets.Release,
        Play_Button55_Bomb = TimerIdOffsets.ButtonBegin + 550 + TimerIdOffsets.Bomb,
        Play_Button55_LongBomb = TimerIdOffsets.ButtonBegin + 550 + TimerIdOffsets.LongBomb,
        Play_Button55_Mine = TimerIdOffsets.ButtonBegin + 550 + TimerIdOffsets.Mine,

        Play_Button56_Press = TimerIdOffsets.ButtonBegin + 560 + TimerIdOffsets.Press,
        Play_Button56_Release = TimerIdOffsets.ButtonBegin + 560 + TimerIdOffsets.Release,
        Play_Button56_Bomb = TimerIdOffsets.ButtonBegin + 560 + TimerIdOffsets.Bomb,
        Play_Button56_LongBomb = TimerIdOffsets.ButtonBegin + 560 + TimerIdOffsets.LongBomb,
        Play_Button56_Mine = TimerIdOffsets.ButtonBegin + 560 + TimerIdOffsets.Mine,

        Play_Button57_Press = TimerIdOffsets.ButtonBegin + 570 + TimerIdOffsets.Press,
        Play_Button57_Release = TimerIdOffsets.ButtonBegin + 570 + TimerIdOffsets.Release,
        Play_Button57_Bomb = TimerIdOffsets.ButtonBegin + 570 + TimerIdOffsets.Bomb,
        Play_Button57_LongBomb = TimerIdOffsets.ButtonBegin + 570 + TimerIdOffsets.LongBomb,
        Play_Button57_Mine = TimerIdOffsets.ButtonBegin + 570 + TimerIdOffsets.Mine,

        Play_Button58_Press = TimerIdOffsets.ButtonBegin + 580 + TimerIdOffsets.Press,
        Play_Button58_Release = TimerIdOffsets.ButtonBegin + 580 + TimerIdOffsets.Release,
        Play_Button58_Bomb = TimerIdOffsets.ButtonBegin + 580 + TimerIdOffsets.Bomb,
        Play_Button58_LongBomb = TimerIdOffsets.ButtonBegin + 580 + TimerIdOffsets.LongBomb,
        Play_Button58_Mine = TimerIdOffsets.ButtonBegin + 580 + TimerIdOffsets.Mine,

        Play_Button59_Press = TimerIdOffsets.ButtonBegin + 590 + TimerIdOffsets.Press,
        Play_Button59_Release = TimerIdOffsets.ButtonBegin + 590 + TimerIdOffsets.Release,
        Play_Button59_Bomb = TimerIdOffsets.ButtonBegin + 590 + TimerIdOffsets.Bomb,
        Play_Button59_LongBomb = TimerIdOffsets.ButtonBegin + 590 + TimerIdOffsets.LongBomb,
        Play_Button59_Mine = TimerIdOffsets.ButtonBegin + 590 + TimerIdOffsets.Mine,

        Play_Button60_Press = TimerIdOffsets.ButtonBegin + 600 + TimerIdOffsets.Press,
        Play_Button60_Release = TimerIdOffsets.ButtonBegin + 600 + TimerIdOffsets.Release,
        Play_Button60_Bomb = TimerIdOffsets.ButtonBegin + 600 + TimerIdOffsets.Bomb,
        Play_Button60_LongBomb = TimerIdOffsets.ButtonBegin + 600 + TimerIdOffsets.LongBomb,
        Play_Button60_Mine = TimerIdOffsets.ButtonBegin + 600 + TimerIdOffsets.Mine,

        Play_Button61_Press = TimerIdOffsets.ButtonBegin + 610 + TimerIdOffsets.Press,
        Play_Button61_Release = TimerIdOffsets.ButtonBegin + 610 + TimerIdOffsets.Release,
        Play_Button61_Bomb = TimerIdOffsets.ButtonBegin + 610 + TimerIdOffsets.Bomb,
        Play_Button61_LongBomb = TimerIdOffsets.ButtonBegin + 610 + TimerIdOffsets.LongBomb,
        Play_Button61_Mine = TimerIdOffsets.ButtonBegin + 610 + TimerIdOffsets.Mine,

        Play_Button62_Press = TimerIdOffsets.ButtonBegin + 620 + TimerIdOffsets.Press,
        Play_Button62_Release = TimerIdOffsets.ButtonBegin + 620 + TimerIdOffsets.Release,
        Play_Button62_Bomb = TimerIdOffsets.ButtonBegin + 620 + TimerIdOffsets.Bomb,
        Play_Button62_LongBomb = TimerIdOffsets.ButtonBegin + 620 + TimerIdOffsets.LongBomb,
        Play_Button62_Mine = TimerIdOffsets.ButtonBegin + 620 + TimerIdOffsets.Mine,

        Play_Button63_Press = TimerIdOffsets.ButtonBegin + 630 + TimerIdOffsets.Press,
        Play_Button63_Release = TimerIdOffsets.ButtonBegin + 630 + TimerIdOffsets.Release,
        Play_Button63_Bomb = TimerIdOffsets.ButtonBegin + 630 + TimerIdOffsets.Bomb,
        Play_Button63_LongBomb = TimerIdOffsets.ButtonBegin + 630 + TimerIdOffsets.LongBomb,
        Play_Button63_Mine = TimerIdOffsets.ButtonBegin + 630 + TimerIdOffsets.Mine,

        Play_Button64_Press = TimerIdOffsets.ButtonBegin + 640 + TimerIdOffsets.Press,
        Play_Button64_Release = TimerIdOffsets.ButtonBegin + 640 + TimerIdOffsets.Release,
        Play_Button64_Bomb = TimerIdOffsets.ButtonBegin + 640 + TimerIdOffsets.Bomb,
        Play_Button64_LongBomb = TimerIdOffsets.ButtonBegin + 640 + TimerIdOffsets.LongBomb,
        Play_Button64_Mine = TimerIdOffsets.ButtonBegin + 640 + TimerIdOffsets.Mine,

        Play_Button65_Press = TimerIdOffsets.ButtonBegin + 650 + TimerIdOffsets.Press,
        Play_Button65_Release = TimerIdOffsets.ButtonBegin + 650 + TimerIdOffsets.Release,
        Play_Button65_Bomb = TimerIdOffsets.ButtonBegin + 650 + TimerIdOffsets.Bomb,
        Play_Button65_LongBomb = TimerIdOffsets.ButtonBegin + 650 + TimerIdOffsets.LongBomb,
        Play_Button65_Mine = TimerIdOffsets.ButtonBegin + 650 + TimerIdOffsets.Mine,

        Play_Button66_Press = TimerIdOffsets.ButtonBegin + 660 + TimerIdOffsets.Press,
        Play_Button66_Release = TimerIdOffsets.ButtonBegin + 660 + TimerIdOffsets.Release,
        Play_Button66_Bomb = TimerIdOffsets.ButtonBegin + 660 + TimerIdOffsets.Bomb,
        Play_Button66_LongBomb = TimerIdOffsets.ButtonBegin + 660 + TimerIdOffsets.LongBomb,
        Play_Button66_Mine = TimerIdOffsets.ButtonBegin + 660 + TimerIdOffsets.Mine,

        Play_Button67_Press = TimerIdOffsets.ButtonBegin + 670 + TimerIdOffsets.Press,
        Play_Button67_Release = TimerIdOffsets.ButtonBegin + 670 + TimerIdOffsets.Release,
        Play_Button67_Bomb = TimerIdOffsets.ButtonBegin + 670 + TimerIdOffsets.Bomb,
        Play_Button67_LongBomb = TimerIdOffsets.ButtonBegin + 670 + TimerIdOffsets.LongBomb,
        Play_Button67_Mine = TimerIdOffsets.ButtonBegin + 670 + TimerIdOffsets.Mine,

        Play_Button68_Press = TimerIdOffsets.ButtonBegin + 680 + TimerIdOffsets.Press,
        Play_Button68_Release = TimerIdOffsets.ButtonBegin + 680 + TimerIdOffsets.Release,
        Play_Button68_Bomb = TimerIdOffsets.ButtonBegin + 680 + TimerIdOffsets.Bomb,
        Play_Button68_LongBomb = TimerIdOffsets.ButtonBegin + 680 + TimerIdOffsets.LongBomb,
        Play_Button68_Mine = TimerIdOffsets.ButtonBegin + 680 + TimerIdOffsets.Mine,

        Play_Button69_Press = TimerIdOffsets.ButtonBegin + 690 + TimerIdOffsets.Press,
        Play_Button69_Release = TimerIdOffsets.ButtonBegin + 690 + TimerIdOffsets.Release,
        Play_Button69_Bomb = TimerIdOffsets.ButtonBegin + 690 + TimerIdOffsets.Bomb,
        Play_Button69_LongBomb = TimerIdOffsets.ButtonBegin + 690 + TimerIdOffsets.LongBomb,
        Play_Button69_Mine = TimerIdOffsets.ButtonBegin + 690 + TimerIdOffsets.Mine,

        Play_Button70_Press = TimerIdOffsets.ButtonBegin + 700 + TimerIdOffsets.Press,
        Play_Button70_Release = TimerIdOffsets.ButtonBegin + 700 + TimerIdOffsets.Release,
        Play_Button70_Bomb = TimerIdOffsets.ButtonBegin + 700 + TimerIdOffsets.Bomb,
        Play_Button70_LongBomb = TimerIdOffsets.ButtonBegin + 700 + TimerIdOffsets.LongBomb,
        Play_Button70_Mine = TimerIdOffsets.ButtonBegin + 700 + TimerIdOffsets.Mine,

        Play_Button71_Press = TimerIdOffsets.ButtonBegin + 710 + TimerIdOffsets.Press,
        Play_Button71_Release = TimerIdOffsets.ButtonBegin + 710 + TimerIdOffsets.Release,
        Play_Button71_Bomb = TimerIdOffsets.ButtonBegin + 710 + TimerIdOffsets.Bomb,
        Play_Button71_LongBomb = TimerIdOffsets.ButtonBegin + 710 + TimerIdOffsets.LongBomb,
        Play_Button71_Mine = TimerIdOffsets.ButtonBegin + 710 + TimerIdOffsets.Mine,
    }
}
