<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\Media\LivreNoirLibrary.Media.Bitmap\Structs\DoubleRect.cs" Link="src\DoubleRect.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\LivreNoirLibrary.Core\LivreNoirLibrary.Core.csproj" />
  </ItemGroup>

</Project>
