<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	  <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	  <BaseOutputPath>..\bin</BaseOutputPath>
	  <Authors>Kuroki-Narumi</Authors>
	  <Company>LivreNoir</Company>
	  <AllowedReferenceRelatedFileExtensions>
		  *.xml;
		  *.pdb
	  </AllowedReferenceRelatedFileExtensions>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\LivreNoirLibrary.Core\LivreNoirLibrary.Core.csproj" />
		<ProjectReference Include="..\LivreNoirLibrary.SourceGenerator\LivreNoirLibrary.SourceGenerator.csproj">
			<OutputItemType>Analyzer</OutputItemType>
			<ReferenceOutputAssembly>false</ReferenceOutputAssembly>
		</ProjectReference>
		<ProjectReference Include="..\LivreNoirLibrary.Wpf\LivreNoirLibrary.Wpf.csproj" />
	</ItemGroup>

</Project>
