<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<Authors>Kuroki-Narumi</Authors>
		<Company>LivreNoir</Company>
		<RepositoryUrl>https://github.com/Kuroki-Narumi/LivreNoirLibrary10</RepositoryUrl>
		<RootNamespace>LivreNoirLibrary.Media.Integrated</RootNamespace>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<BaseOutputPath>..\..\bin</BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\LivreNoirLibrary.Media.Bms\LivreNoirLibrary.Media.Bms.csproj" />
	  <ProjectReference Include="..\LivreNoirLibrary.Media.Midi\LivreNoirLibrary.Media.Midi.csproj" />
	  <ProjectReference Include="..\LivreNoirLibrary.Media.Wave\LivreNoirLibrary.Media.Wave.csproj" />
	</ItemGroup>

</Project>
