
namespace LivreNoirLibrary.Media.Bms
{
    public enum Channel : short
    {
        None = 0,
        Bgm = 1,
        Bar = 2,

        Bpm_Base = 3,
        Bpm = 8,
        Stop = 9,

        Ext = 5,

        Bga_Base = 4,
        Bga_Layer1 = 7,
        Bga_Layer2 = 10,
        Bga_Poor = 6,
        Opacity_Base = 11,
        Opacity_Layer1 = 12,
        Opacity_Layer2 = 13,
        Opacity_Poor = 14,

        Visible_Start = 36,
        Visible_End = 107,
        Invisible_Start = 108,
        Invisible_End = 179,
        Long_Start = 180,
        Long_End = 251,
        Mine_Start = 468,
        Mine_End = 539,

        Bgm_Volume = 331,
        Key_Volume = 332,
        Text = 333,
        ExRank = 360,
        Argb_Base = 361,
        Argb_Layer1 = 362,
        Argb_Layer2 = 363,
        Argb_Poor = 364,
        SwBga = 365,
        ChangeOption = 366,

        Scroll = 1020,
        Speed = 1033,

        Bgm_Start = 1296,
        Bgm_End = 14255,

        Beat_1P_1 = Visible_Start + 1,
        Beat_1P_2 = Visible_Start + 2,
        Beat_1P_3 = Visible_Start + 3,
        Beat_1P_4 = Visible_Start + 4,
        Beat_1P_5 = Visible_Start + 5,
        Beat_1P_6 = Visible_Start + 8,
        Beat_1P_7 = Visible_Start + 9,
        Beat_1P_Scratch = Visible_Start + 6,
        Beat_1P_Ext = Visible_Start + 7,

        Beat_2P_1 = Visible_Start + 37,
        Beat_2P_2 = Visible_Start + 38,
        Beat_2P_3 = Visible_Start + 39,
        Beat_2P_4 = Visible_Start + 40,
        Beat_2P_5 = Visible_Start + 41,
        Beat_2P_6 = Visible_Start + 44,
        Beat_2P_7 = Visible_Start + 45,
        Beat_2P_Scratch = Visible_Start + 42,
        Beat_2P_Ext = Visible_Start + 43,

        Popn_1 = Beat_1P_1,
        Popn_2 = Beat_1P_2,
        Popn_3 = Beat_1P_3,
        Popn_4 = Beat_1P_4,
        Popn_5 = Beat_1P_5,
        Popn_6 = Beat_2P_2,
        Popn_7 = Beat_2P_3,
        Popn_8 = Beat_2P_4,
        Popn_9 = Beat_2P_5,

        Popn_1P_1 = Beat_1P_1,
        Popn_1P_2 = Beat_1P_2,
        Popn_1P_3 = Beat_1P_3,
        Popn_1P_4 = Beat_1P_4,
        Popn_1P_5 = Beat_1P_5,
        Popn_1P_6 = Beat_1P_6,
        Popn_1P_7 = Beat_1P_7,
        Popn_1P_8 = Beat_1P_Scratch,
        Popn_1P_9 = Beat_1P_Ext,
        Popn_2P_1 = Beat_2P_1,
        Popn_2P_2 = Beat_2P_2,
        Popn_2P_3 = Beat_2P_3,
        Popn_2P_4 = Beat_2P_4,
        Popn_2P_5 = Beat_2P_5,
        Popn_2P_6 = Beat_2P_6,
        Popn_2P_7 = Beat_2P_7,
        Popn_2P_8 = Beat_2P_Scratch,
        Popn_2P_9 = Beat_2P_Ext,
    }
}
