<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.22621.0</TargetFramework>
    <RootNamespace>LivreNoir.YuGiOhDatabase</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
	  <BaseOutputPath>..\..\bin</BaseOutputPath>
	  <AllowedReferenceRelatedFileExtensions>
		  *.xml;
		  *.pdb
	  </AllowedReferenceRelatedFileExtensions>
    <UseWPF>true</UseWPF>
	  <ApplicationManifest>app.manifest</ApplicationManifest>
	  <ApplicationIcon>icon.ico</ApplicationIcon>
	  <Version>2.0.0</Version>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

  <ItemGroup>
    <SplashScreen Include="..\..\YuGiOh\LivreNoirLibrary.YuGiOh.Core\Resources\splash.png" Link="splash.png" />
    <Content Include="icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Windows\LivreNoirLibrary.Windows.Capture\LivreNoirLibrary.Windows.Capture.csproj" />
    <ProjectReference Include="..\..\Windows\LivreNoirLibrary.Windows.Controls\LivreNoirLibrary.Windows.Controls.csproj" />
    <ProjectReference Include="..\..\YuGiOh\LivreNoirLibrary.Windows.YuGiOh\LivreNoirLibrary.Windows.YuGiOh.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="src\Unit_DuelLog.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
